# Generated by Django 6.0 on 2026-05-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_role_book_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_product',
            unique_together=set(),
        ),
    ]
