# Generated by Django 6.0 on 2026-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_book_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
