# Generated by Django 6.0 on 2026-05-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_book_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_product',
            name='price',
        ),
        migrations.AddField(
            model_name='add_product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
