# Generated by Django 6.0 on 2026-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_book_product_price_add_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_product',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
