# Generated by Django 5.2.1 on 2026-05-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_add_product_id_alter_book_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='name',
            new_name='user',
        ),
    ]
