# Generated by Django 5.2.1 on 2026-05-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_name_manager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='user',
            new_name='users',
        ),
    ]
