# Generated by Django 5.2.1 on 2026-05-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_user_add_product_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='users',
            new_name='user',
        ),
    ]
