# Generated by Django 5.2.1 on 2026-05-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_users_add_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='user',
            new_name='users',
        ),
    ]
